### ISSUE TITLE
Error attempting to authenticate

### ISSUE THREAD

**Issue by austinsc** [krauskopf/node-red-contrib-car-bmw#1]
Getting an error 'ENOENT: no such file or directory, open 'currenttoken.json''
Failed to read token: Couldn't find token in response

I've tried the default URL as well as 'connecteddrive.bmwusa.com'

**Comment by krauskopf** [comment]
Please try again with https://b2vapi.bmwgroup.us

**Comment by austinsc** [comment]
hmm i tried it and no error this time but no output either. I'll keep digging, thanks for the help.
