### ISSUE TITLE
Not an issue: feature request

### ISSUE THREAD

**Issue by bbwouters** [krauskopf/node-red-contrib-car-bmw#10]
Would it be possible to add an action: 

Initiate Charging
If the vehicle is plugged in, but not charging (due to an off peak setting?) it is possible to force the car to charge.

serviceType=CHARGE_NOW

With current focus on energy it would allow to trigger a charging session when there is an excess of solar energy or net capacity is available in these countries where you have capacity penalties.

Much appreciated

**Comment by krauskopf** [comment]
I have added the service, but did not have a chance to test it. Please give it a try and report back. Thanks and regards.

**Comment by bbwouters** [comment]
I get the following error for the charging command: 
23/01/2022, 19:30:43node: 28196ee954d44ac8
msg : error
"Error: Server http statusCode 502"

Flashing headlights etc.. works with no issue.

**Comment by bbwouters** [comment]
Installing the BMW node on a second instance gives (me) an error:

node-red-contrib-car-bmw
0.3.2
SyntaxError: Unexpected token = (line:27)
car-bmw


2022-01-30T13:44:00.012Z Install : node-red-contrib-car-bmw 0.3.2

2022-01-30T13:44:02.036Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-car-bmw@0.3.2
2022-01-30T13:44:05.952Z [out] + node-red-contrib-car-bmw@0.3.2
2022-01-30T13:44:05.952Z [out] added 1 package from 1 contributor in 2.421s
2022-01-30T13:44:06.012Z rc=0

**Comment by klessed** [comment]
Error: Server http statusCode 404: Resource Not Found

**Comment by krauskopf** [comment]
Please try with verson 0.5.3
