### ISSUE TITLE
"Error: Couldn't find token in response"

### ISSUE THREAD

**Issue by na-am** [krauskopf/node-red-contrib-car-bmw#12]
i've this error since yesterday :-(
i tried on different internet connections/locations...  same error message
the app on my mobile phone was not updated and is still working

**Comment by vdjan** [comment]
Same issue for me since yesterday (24/2) :/

**Comment by HeraldCoupe** [comment]
Same problem here. BMW must have changed something again. Looking forward to a fix.

**Comment by na-am** [comment]
it's frustrating... i just installed home assistant on my synology nas/docker and i've to say BMW connected is working there like a charm. less then 5 min. of work/configuration!
so i'll look into the code of HA and convert it for using in Node-red

**Comment by hoschult** [comment]
same problem here; trying to find out what might changed

**Comment by Donni1966** [comment]
thanx for this info - for me no way, i am not an programmer :-/ So can help here

**Comment by michaefa** [comment]
Hi Sebastian, it would be great if you could fix this. I really appreciate your work and really like the bmw-node. Can I donate you a coffee somewhere?

**Comment by peterossege** [comment]
I would donate another coffee ;-)

**Comment by thomasp3** [comment]
> I would donate another coffee ;-)

Me too!

**Comment by Donni1966** [comment]
me too - or may two coffees :-)

**Comment by krauskopf** [comment]
Thanks for the willingness to donate. Glad to hear that my work is appreciated. :-)
Found some time and motivation to implement a quick fix in the last hours. I didn't have time to do a full test, yet. But you might give it a try. At least the basics should work ;-)

**Comment by Donni1966** [comment]
that's right. Basic are running again. Thanx a lot. It is really amazing how the community works. For me unbelievable how to fix all the time the issue without getting money only praise. 
So i spend a little coffee with PayPal - hope this will come to you.

**Comment by michaefa** [comment]
Thanks a lot! Hope the coffee will arrive!

**Comment by krauskopf** [comment]
Glad to hear, that it is working again. Thanks a lot for the coffee :-). That's more than enough. I almost don't dare to accept that. I created the nodes for fun and the community spirit. Happy to hear, that is actually used out there.

**Comment by Donni1966** [comment]
Oh i love this node-red model. I may automatic heating an Workdays, loading infos via outspeak and all this nice thinks. But by the way: 
there was nodes with last trip and all trips, where i get more infos about trips an used power on this. Is this not yet part of the interface on mybmw?

**Comment by abryniak** [comment]
Hi, when trying with version 0.4.1 I'm getting the below error code?
_**Error: Server send http statusCode 401 on stage 1**_ 
Can anyone advise with that please?
Thank you

**Comment by Donni1966** [comment]
I test the 0.4.1 - for me it works as fine as the version 0.4
