### ISSUE TITLE
Error: Server http statusCode 503

### ISSUE THREAD

**Issue by michaefa** [krauskopf/node-red-contrib-car-bmw#14]
Since a couple of days I am receiving statusCode 503 with version 0.4.1. Has BMW again changed anything? Are others getting this error too?

**Comment by pl0ink** [comment]
I can confirm the same issue, like that for the last couple of days. 
If I use the BMW Get function with Dynamic it returns a 503, the same BMW Get with e.g. Services works fine. The BMW App works fine, so it looks like it uses different API.
The BMW List function returns much of the same data the GET/Dynamic function does. It has a different structure but the data is there. So this can be an alternative should the original API have changed / be removed.

**Comment by hoschult** [comment]
same here. App works fine as well. try to find out what changed...

**Comment by MarcS071** [comment]
API has changed again. Please check output of BMW list node. All data is available there (in new format) and it seems the 'get' node is not needed at all now.

**Comment by krauskopf** [comment]
Sorry, seems like the API changed again. No idea why. But this time it is not the authentication part. Error tells "Service temporarily unavailable". 
But as @MarcS071 already mentioned, it looks like the LIST node now returns far more information. Might compensate what is missing via the GET node.

**Comment by grasshide** [comment]
I'm only getting an empty array from the list node. App works fine.

**Comment by michaefa** [comment]
same with me. maybe there is a difference between Mini or BMW?
Kind regards,
Michael

Am 22. April 2022 17:49:13 schrieb grasshide ***@***.***>:

**Comment by Toxo666** [comment]
And the "last update reason" is missing. This was a trigger that i used for logging my rides.
i have compared what the list node is throwing out on start ride/end ride/doors locked/etc. the only different params are lat,lon and date.
Thats not really enough for me.

any ideas?

**Comment by pl0ink** [comment]
There is no real equivalent for that I think, i thought i found a way with:

properties: object
lastUpdatedAt: "2022-05-01T22:45:31Z"
inMotion: false
areDoorsLocked: true

and hoped to base some logic on those fields, but the "inMotion" is always false even when the car is definitely moving.
Similar the Locked and Secured status difference is also missing...

Also looked at the ioBroker plugin for BMW, they have the same info, so also missing what you are looking for.

**Comment by alexanderbeermann** [comment]
Since a few days I receive values from the GetService. But these values are outdated, for instance latitude, longitude, Adresse formatted. 
It seems to be not an issue of this node, but with the BMW Services. 
I have the Same outdated values weithin the BMW App - even with the latest Update zo Android V2.5.0. 

Are you facing the same issued?

**Comment by Donni1966** [comment]
Hmm. My Mini App and the Homeassistant I use instead run fine. But I get at the moment nothing from the nodes

**Comment by grasshide** [comment]
> Hmm. My Mini App and the Homeassistant I use instead run fine. But I get at the moment nothing from the nodes

Not using HA. The Mini App is fine though. The node gives me:
29 May 16:13:00 - [error] [car-bmw-get:Mini] Error: Server http statusCode 503

12. April 2022 8:00 am (Germany/Berlin time) was the last time I received anything from the node.

**Comment by krauskopf** [comment]
I changed all service to BMW api v4 with release v0.5.0, so I hope anyone has a solution and think this issue is outdated anyway.
