### ISSUE TITLE
Error: Server http statusCode 403

### ISSUE THREAD

**Issue by Blodstrupmo1** [krauskopf/node-red-contrib-car-bmw#15]
I started receiving "Error: Server http statusCode 403" when i try to update node "BMW list" version 0.4.1.

**Comment by OABsoftware** [comment]
Same here.
The https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles returns a 403 error.

**Comment by Miki433** [comment]
Same Problem since 2 days...

**Comment by OABsoftware** [comment]
Please update row 290 of bmw.js to:
          'x-user-agent': 'android(SP1A.210812.016.C1);bmw;2.5.2(14945);row',

**Comment by Miki433** [comment]
> Please update row 290 of bmw.js to: 'x-user-agent': 'android(SP1A.210812.016.C1);bmw;2.5.2(14945);row',

worked great, thanks!

**Comment by Blodstrupmo1** [comment]
> agent

Worked here also. Thanks 😃

**Comment by Blodstrupmo1** [comment]
> Please update row 290 of bmw.js to:
> 
>           'x-user-agent': 'android(SP1A.210812.016.C1);bmw;2.5.2(14945);row',
> 
> 

Worked here also. Thanks 😃

**Comment by krauskopf** [comment]
Made a release (v4.0.3), based on the contributions from @OABsoftware and @dzett. Thanks! 
Please give it a try.

**Comment by OABsoftware** [comment]
I found out that the "row" part at the end of the user agent string is the abbreviation of "rest of world".
If your region is North America, "row" should be replaced by "na".
It it is China, it should be "cn".
So the last part of the user agent string needs to be made region dependant.

**Comment by oemich** [comment]
Hi @Donni1966, at least for BMW it is working with the list node. I selected in the List node as Output "as multiple messages, one per car" and receive two messages for my cars.  In the message.payload I find most of the needed information in the "properties" Object (e.g. door status, fuel level and combined rangem) and "status" object (e.g. currentMileage).

**Comment by Donni1966** [comment]
that's the problem - I get with list and empty array. 

no info inside

> I cross checked with [bimmer_connected ](https://github.com/bimmerconnected/bimmer_connected/)and it seems that the user agent `'x-user-agent': 'android(SP1A.210812.016.C1);bmw;2.5.2(14945)',` also contains the info of which brand app is requesting data (bmw or mini) maybe there is a check on the API for it?
 
sorry do not understand this

**Comment by oemich** [comment]
Hi @Donni1966 ,

can you check if my modification helps? You would need to install the module out of my forked and modified repository: https://github.com/oemich/node-red-contrib-car-bmw if you report that it works, I could incorporate it also here.

I cannot verify it by my own as I have no mini to test.

**Comment by Donni1966** [comment]
@oemich i installed via palette the version 0.4.4 and i try a List request -> result: Empty array :-/  or is there a way to install your fork? Do not know exactly how to do this

**Comment by oemich** [comment]
@Donni1966 you would need to install it differently:
1. Uninstall todays node
2. Got to your nodered installation folder in the terminal and perfom `npm install https://github.com/oemich/node-red-contrib-car-bmw` (https://nodered.org/docs/user-guide/runtime/adding-nodes#installing-with-npm)
3. Restart nodered to see the newly installed node 

Now you can try it ... the node is named the same way as from the original repository here.

**Comment by Donni1966** [comment]
puh that's mean I have to delete alle nodes with this config, deinstall and reinstall and configure again. For this I need more time as I have in the moment. it is possible to stop node-red install in the folder and start again?

**Comment by oemich** [comment]
I just tried it, and yes this would also work. 
* Stop your node Red
* install the Updated "node" from my repository `npm install https://github.com/oemich/node-red-contrib-car-bmw`
* Start your node red and test

Don't forget to install the original package after the test ... same steps as above just replace the `npm install` step with `npm install node-red-contrib-car-bmw`

If you confirm that it works with the change, I will create a Pull Request with a configurable option for the manufacturer.

**Comment by Donni1966** [comment]
thanx @oemich for the instruction - but no changes. Still and empty array :-/ so, looks like only bmw cars are listed. 
so i finally switch to Home Assistant and read the data from there to put in on the dashboard. 
The switches like Horn, Climatic on off ans lock system works fine. the charging statistic also. 
for me at the moment works fine. Thanx for helping and trying
