### ISSUE TITLE
Distances in miles instead of km

### ISSUE THREAD

**Issue by oemlerm** [krauskopf/node-red-contrib-car-bmw#17]
It seems that the BMW API changed its defaulting. In the Response from the "List" node I get units in imperial format ("mi" instead of "km" and "gal" instead of "l"). It seems that only the "Status" element with its sub elements is affected, the "properties" element is still metric. 

Example from msg.payload.status:
`{"lastUpdatedAt":"2022-06-14T06:14:51Z","currentMileage":{"mileage":4970,"units":"mi","formattedMileage":"4,970"}, ...}`

Affected elements are:
- currentMileage
- requiredServices
- fuelIndicators

I found a related issue and fix on https://github.com/bimmerconnected/bimmer_connected/pull/449

**Comment by oemich** [comment]
I created a PR #18 to fix this
