### ISSUE TITLE
Error: Server http statusCode 400

### ISSUE THREAD

**Issue by ma44t** [krauskopf/node-red-contrib-car-bmw#20]
I'm continuously getting  "Error: Server http statusCode 400" as an answer in Node-RED when using the BMW Get node and selecting Services or Service Partner in the Data type. It's rare because I don't get any error when selecting Charging Statistics or Charging Sessions in the Data type and it works well, giving the expected answer. 

¿Does anyone know what's going on? I'm using version 0.4.5 with a BMW i3.

Thank you!

**Comment by krauskopf** [comment]
If still interested, then please try again with v0.5.1. If you still get the error, then reopen a new issue. Thanks.

**Comment by greytuk** [comment]
Just to update, issue still remains with 0.51
