### ISSUE TITLE
Getting Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by mlaber** [krauskopf/node-red-contrib-car-bmw#21]
With 0.4.6 the car-bmw-get node receives "Getting Error: connect ECONNREFUSED" for most data types. Only charging statistics and charging sessions works. Car is a 2017 i3

**Comment by vdjan** [comment]
Yep same issue, also the List node seems not to give me updated data since yesterday :/

**Comment by Michael-Hennemann** [comment]
Also seeing the "Getting Error: connect ECONNREFUSED" with 0.4.6 with the "get node"
"List node" seems to work though...

**Comment by wkirmair** [comment]
Same here with 0.4.6 since a few days.
"Error: Server http statusCode 403" with BMW List
and 
"Error: connect ECONNREFUSED 160.46.245.252:443" with BMW Get Dynamic, Services and Service Partner.
Only BMW Get Charging Statistics and Charging Sessions works.

**Comment by krauskopf** [comment]
The services `Dynamic`, `Services` and `Service Partner` are no longer supported by the BMW API, but you find all the relevant information via the `State` service. The structure of the returned json is similar but not the same.
