### ISSUE TITLE
Server send http statusCode 200 on stage 2

### ISSUE THREAD

**Issue by greytuk** [krauskopf/node-red-contrib-car-bmw#24]
When trying to get data using BMW-List (V0.4.7 and 0.4.6) from the USA website I get the error

Error: Server send http statusCode 200 on stage 2

If I enter my incorrect logon details and test again then it will fail at stage 1, so I am confident logon details are correct.

I doubt this is related, but I also have a BMW in the UK, and using the "rest of the world" for region and BMW-List works fine for this account.

**Comment by collinscochran** [comment]
I also have this same issue, is there any recommended fix?

**Comment by greytuk** [comment]
Just to confirm, issue remains on 0.51

**Comment by krauskopf** [comment]
Is your car or your node-red server located in the USA? Or both?

The BMW in UK is connected to a different Connected-Drive account?

**Comment by greytuk** [comment]
Hi,

node red server is in the U.K.

UK car is connected to “rest of the world” option in Node Red and works fine.

USA car is using USA in Node red and fails with the 200 error.

I can log into the BMW USA  connected drive website without issue. If I enter the incorrect password in Node Red then the error will change. Everything seems to indicate that Node Red just doesn’t expect the BMW api response.

**Comment by krauskopf** [comment]
Agree with you. Seems like my code is not yet working for USA. Looks like there are different OAuth servers. Will try to replicate the code from https://github.com/bimmerconnected/bimmer_connected/blob/48d4c14d111bd2213bb1109cddbf812efa4af7ef/bimmer_connected/api/authentication.py#L139C34-L139C34 
But will take a few days.

**Comment by greytuk** [comment]
Thanks - appreciate the work you have put into this.

**Comment by simmonslr** [comment]
Has anyone found a workaround or fix for this problem? Would really like to put this to use.

**Comment by wkirmair** [comment]
I'm getting the same error message on an i3s located in Germany, NodeRed 3.1.9 / node-red-contrib-car-bmw 0.5.3 also located in Germany on all Nodes (get/list/action).

**Comment by IfThenElseLoop** [comment]
Same for me. Since yesterday evening it does not work anymore. Location: Germany. Car: BMW iX1.
Message: "Error: Server send http statusCode 200 on stage 2"
Independent what is requested (status, charging history). No idea yet, what could happen here. Especially as the status is 200 which means request was successfully.

**Comment by locke987** [comment]
Same for me

**Comment by kranze** [comment]
Same here, Germany BMW i3 Node Red 3.1.3

**Comment by juergenarchan** [comment]
Same here. Austria BMW X3, Node Red 3.1.3

**Comment by cedricboitte** [comment]
Same issue here . Belgium . Bmw i4, node red 3.1.8 .
Before Error: Server send http statusCode 200 on stage 2 it was Error: Server http statusCode 404....

**Comment by rsteininger** [comment]
Hi there, 
Mine had been working for a long time but it stopped working 2 days ago: 
Last fetched: 11/04/2024 14:25:21
I don't recall doing any updates before then! However, my BMW App on my Android phone has received an update, round about the time it stopped working! 
Could someone please investigate? 
THANKS

**Comment by Kawa1100** [comment]
Hi, same for me since at least two days, Location: Germany, Car: BMW iX1, Node Red 3.1.8.
Any update is welcome.
Thank you very much in advance!

**Comment by kranze** [comment]
This PR worked for me:

https://github.com/krauskopf/node-red-contrib-car-bmw/pull/39

**Comment by FotoLexi** [comment]
I had the same issue since I updated to version 0.6.0, now I have this error "TypeError: randomUUID is not a function"

**Comment by Miki433** [comment]
Same Problem as FotoLexi- randomUUID is not a function

**Comment by Kawa1100** [comment]
Works fine for me again with version 0.6.0. Thank you so much! Great!

**Comment by IfThenElseLoop** [comment]
> Works fine for me again with version 0.6.0. Thank you so much! Great!

Interesting that it works for you, I also updated to 0.6.0 and now get the "randomUUID" Error.

**Comment by IfThenElseLoop** [comment]
It seems that the error "TypeError: randomUUID is not a function" is related to an old node.js version. I use redmatic on a raspberrymatic installation and uses node.js version 14.16.0. But the randomUUID function is available with node.js v15.5.0. So Kawa1100 seems to use a setup with a newer node.js version.
There is now new version of redmatic so maybe there is a possibility to upgrade node.js, not sure.

**Comment by IfThenElseLoop** [comment]
I have now also updated to redmatic 7.3.5, and it works again.
👍

**Comment by ChrisIDS6** [comment]
Update worked --> Thanks a lot for your time & knowlege
