### ISSUE TITLE
 SyntaxError: Unexpected token = (line:27)

### ISSUE THREAD

**Issue by fss-itsupport** [krauskopf/node-red-contrib-car-bmw#26]
Hi
Just tried to use this and when installing via Node-red pallette manager the install reports

SyntaxError: Unexpected token = (line:27)

Which if I then deploy a it stops all flows from working due to the error.

**Comment by krauskopf** [comment]
Hi,

either your Node-RED or nodejs installation is too old. I would recommend to upgrade to:
Node-RED >= v3.x
Node.js >= v18.x
