### ISSUE TITLE
Error: Server send http statusCode 401 on stage 1

### ISSUE THREAD

**Issue by ChrisIDS6** [krauskopf/node-red-contrib-car-bmw#29]
Hi, 

since yesterday I recive "Error: Server send http statusCode 401 on stage 1" in node red, when I send a request to my BMW....

Any idea what happens?

Thanks for your help.

**Comment by ChrisIDS6** [comment]
I solved it, by changing my Password ;)

**Comment by unix1234** [comment]
me too (after updating node-red to update the node...) 😅👍

**Comment by CONSULitAS** [comment]
> I solved it
So you could close the issue. 😁 

BTW: Had the same problem, changing Password solved, too.
