### ISSUE TITLE
Error: Server http statusCode 404

### ISSUE THREAD

**Issue by ChrisIDS6** [krauskopf/node-red-contrib-car-bmw#30]
Has anyone also this Problem?

**Comment by greytuk** [comment]
Yes - started for me within the last 24 hours

**Comment by ChrisIDS6** [comment]
Me too, seems to be a Server Problem...

**Comment by MarcS071** [comment]
Same here for 2 days now, I think BMW changed the server? App works fine.

**Comment by arneman** [comment]
Seems like BMW has shut down the v1 API (that is used here) https://forum.iobroker.net/topic/66509/bmw-adapter-404-ressource-not-found/5
@krauskopf

**Comment by jkellerer** [comment]
Here's another reference: https://github.com/bimmerconnected/bimmer_connected/issues/544

It needs some changes. The `/v4/vehicles` endpoint returned just a subset of data and the details need to be fetched from `/v4/vehicles/state`. See: https://github.com/bimmerconnected/bimmer_connected/blob/master/bimmer_connected/account.py#L86

**Comment by jkellerer** [comment]
A quick check with 

```js
  async getCarList() {
    return (await this.get(Bmw._getApiServerNew(this._region), `/eadrax-vcs/v4/vehicles`)).map(async car => {
        let headers = {'bmw-vin': car["vin"]};
        car.state = await this.get(Bmw._getApiServerNew(this._region), `/eadrax-vcs/v4/vehicles/state?apptimezone=0&appDateTime=${new Date().getTime()}&tireGuardMode=ENABLED`, headers);
        return car;
    });
  }
```

shows that the services provide the same (or at least similar) data. However `vehicles/state` is only partially JSON as it seem. Returns "state={...} capabilities={...}" and requires custom parsing.

Try to prepare a PR if I find the time this week.

**Comment by krauskopf** [comment]
I made a quickfix based on the code and info from @jkellerer. Credits go to him. Thanks for the groundwork!

Please notice, that I introduced a new service "state" which now holds most of the interesting vehicle information:
![grafik](https://github.com/krauskopf/node-red-contrib-car-bmw/assets/1938031/0da4135a-4085-4495-8bee-e5609601b4f4)

Example flow to read all states of all cars:
![grafik](https://github.com/krauskopf/node-red-contrib-car-bmw/assets/1938031/960103cf-4a8d-4731-8a3b-845741d0920c)

`[{"id":"50743fa0.f3ba5","type":"inject","z":"77482163.aa1be","name":"","props":[{"p":"payload","v":"","vt":"date"},{"p":"topic","v":"","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":120,"wires":[["83f261b6.ae49b"]]},{"id":"83f261b6.ae49b","type":"car-bmw-list","z":"77482163.aa1be","account":"20974e09.9f9e82","name":"","as":"multi","x":380,"y":120,"wires":[["14e76857.f58c78","cb4090a2.e4aac8"]]},{"id":"14e76857.f58c78","type":"debug","z":"77482163.aa1be","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":630,"y":120,"wires":[]},{"id":"26e62839.e6ff8","type":"car-bmw-get","z":"77482163.aa1be","account":"20974e09.9f9e82","name":"","datatype":"state","x":770,"y":160,"wires":[["717a63b8.7347e4"]]},{"id":"717a63b8.7347e4","type":"debug","z":"77482163.aa1be","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":930,"y":160,"wires":[]},{"id":"cb4090a2.e4aac8","type":"function","z":"77482163.aa1be","name":"","func":"var newMsg = {\n    \"vin\": msg.payload.vin\n}\nreturn newMsg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":620,"y":160,"wires":[["26e62839.e6ff8"]]},{"id":"20974e09.9f9e82","type":"car-bmw","name":"","region":"0","unit":"metric","debug":true}]`

**Comment by greytuk** [comment]
Fix is working well for me. Thanks guys. I think converting from KM to Miles is broken now but that is now big deal.

**Comment by MarcS071** [comment]
Great! Thanks for the really quick fix!

**Comment by ChrisIDS6** [comment]
Thank you, works great!!!
