### ISSUE TITLE
Feature request - open/close all windows

### ISSUE THREAD

**Issue by ChrisIDS6** [krauskopf/node-red-contrib-car-bmw#32]
Its not really an Issues, but at least due to the fact, that there is no possiblity to open/close all windows by the BMW app I think, it could be a nice idea to do this by node red. Maybe its possible.

**Comment by krauskopf** [comment]
Sorry, not aware that it is possible to open/close the windows via remote service. I have this neither in the myBMW app nor is it supported by other libs like bimmer-connected.
