### ISSUE TITLE
Feature Request add Actions

### ISSUE THREAD

**Issue by sincze** [krauskopf/node-red-contrib-car-bmw#35]
While studying the official https://bimmer-connected.readthedocs.io/_/downloads/en/latest/pdf/
documentation I wondered if the following ACTIONS could be added for EV drivers.

chargingsettings: (https://github.com/krauskopf/node-red-contrib-car-bmw/issues/28)
--target-soc 
--ac-limit 

Assumed fixed: Action: Charge Now ?, maybe update the node documentation as well with this command ;-)
charge: (https://github.com/krauskopf/node-red-contrib-car-bmw/issues/10)
- start . stop

**Comment by krauskopf** [comment]
Hi @sincze,

I have added some experimental features to v0.5.1. But I have to say, that it did not work with my 330e. But as it is only a plugin-hybrid I am not sure if it related to my car. Maybe you wanna give it a try:

![grafik](https://github.com/krauskopf/node-red-contrib-car-bmw/assets/1938031/f0b0b4d9-80f3-42ac-846b-f005160f705c)

```
[{"id":"f836278c59e8bd77","type":"function","z":"77482163.aa1be","name":"Set ac limit and target value","func":"\nmsg.payload = {\n    \"chargingTarget\": 80, \n    \"acLimitValue\": 6\n}\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":340,"y":2580,"wires":[["98cdd5e0ecf56e2b"]]},{"id":"dc3ed992da4ec921","type":"inject","z":"77482163.aa1be","name":"","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":120,"y":2580,"wires":[["f836278c59e8bd77"]]},{"id":"98cdd5e0ecf56e2b","type":"car-bmw-action","z":"77482163.aa1be","account":"20974e09.9f9e82","name":"","action":"CHANGE_CHARGING_SETTINGS","x":660,"y":2580,"wires":[["6a3422370f80fdd9"]]},{"id":"6a3422370f80fdd9","type":"debug","z":"77482163.aa1be","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":950,"y":2580,"wires":[]},{"id":"31bc49d40ae0a984","type":"comment","z":"77482163.aa1be","name":"Example: Change AC Limit and battery target value","info":"","x":210,"y":2520,"wires":[]},{"id":"20974e09.9f9e82","type":"car-bmw","name":"","region":"0","unit":"metric","debug":true}]
```

You can read back the current settings with the GET node and the new `Charging Profile` setting:
![grafik](https://github.com/krauskopf/node-red-contrib-car-bmw/assets/1938031/1b467db1-d51c-4f7f-bbed-15978f44e919)

**Comment by sincze** [comment]
![image](https://github.com/krauskopf/node-red-contrib-car-bmw/assets/5776333/c39db83f-a50c-487d-a544-3bbaab193a43)

That seems to work just fine ;-) on i4 (Fully Electric)

**Comment by IfThenElseLoop** [comment]
Just tried setting charging target and ac limit with my iX1, it works :-)
The "Charge Now" action does not work (generates an error): "Error: Server http statusCode 404: Resource Not Found".
Is it possible to start/stop charging another way?
Great work, I use the nodes to integrate with my Homematic Smarthome dashboard.

**Comment by IfThenElseLoop** [comment]
I did some testing and with the help of the bimmer connected document I found the right commands to directly start / stop the charging process. It works fine for my iX1 (at least for all fully electric cars I think it should work). 
I added them to the lib bmw.js and extended the html file to show the additional options.
Here are the relevant sections in bmw.js:
// remote services
...
static SERVICE_CHARGE_START = 'CHARGE_START';
static SERVICE_CHARGE_STOP = 'CHARGE_STOP';
...
async executeRemoteService(vin, service, payload) {
...
case Bmw.SERVICE_CHARGE_START:
return this.execute(vin, 'start-charging');
case Bmw.SERVICE_CHARGE_STOP:
return this.execute(vin, 'stop-charging');

changes to car-bmw.html (below action node section):
...
 "CHARGE_START": "Charge Start",
 "CHARGE_STOP": "Charge Stop",
...
 <option value="CHARGE_START">Charge Start</option>
 <option value="CHARGE_STOP">Charge Stop</option>

Maybe you can include it into the project.

**Comment by krauskopf** [comment]
Thanks @IfThenElseLoop ! I've added the code as you proposed to v0.5.3!

**Comment by IfThenElseLoop** [comment]
> Thanks @IfThenElseLoop ! I've added the code as you proposed to v0.5.3!

Great, just tested the new version and I can confirm it works.

**Comment by krauskopf** [comment]
Great. Thanks for validation!

**Comment by patrickvandenbulcke** [comment]
Hello, I just upgraded to version 0.5.3 and I always get error : Error: Server send http statusCode 401 on stage 1

on each call... so nothing works anymore :(

**Comment by sincze** [comment]
Could be a general issue 403 to much requests (polling). Seems an issue in USA area if you follow the github of bimmer-connected 

It still works on my machine :) (Rest of World)

**Comment by IfThenElseLoop** [comment]
For me it is also still working. Yesterday evening the servers in Europe were not available for several hours (even the App did not work). Today morning it startet working again. Maybe there's an ongoing maintenance.

**Comment by patrickvandenbulcke** [comment]
Hello,

it is working now... strange... must have been a hick up somewhere.

Great addition to the node by the way.... thanks
