### ISSUE TITLE
Server http statusCode 403 - only on status node

### ISSUE THREAD

**Issue by bummzulu** [krauskopf/node-red-contrib-car-bmw#38]
Since today I have been receiving statusCode 403 on the Get Node. Other nodes work fine.

To reproduce just drag a new get node into a flow - configure it correctly and trigger it over an inject node.

Error: 
Error: Server http statusCode 403

The car installed an update today: 11/2023.73 on an i4 eDrive40

**Comment by MarcS071** [comment]
Stopped working here yesterday. Also openWB doensn't work anymore. It seems, BMW changed the API again?

**Comment by jkellerer** [comment]
This might be the related change needed to make it work again https://github.com/bimmerconnected/bimmer_connected/pull/591

**Comment by jkellerer** [comment]
Have a working prototype, PR will be opened soon. Required some changes to the auth flow that bimmer_connected already implemented.
