### ISSUE TITLE
Stopped working today statusCode 401

### ISSUE THREAD

**Issue by MarcS071** [krauskopf/node-red-contrib-car-bmw#42]
[car-bmw-list:BMW] Error: Server send http statusCode 401 on stage 1
Bimmerconnected reports a similar issue.

**Comment by locke987** [comment]
same here since yersterday

**Comment by benninger1** [comment]
same here, changes on the bmw servers like always

**Comment by klessed** [comment]
see https://github.com/home-assistant/core/issues/128598
There appears to be a solution in home assistant coming. Looks like some kind op captcha is required now

**Comment by rsteininger** [comment]
so, before switching to the node-red based function, I had been using the python based "bimmer-connected" (which is also the base function for Home Assistant). They have a command line interface version (CLI) and it seems, they already have solved the issue of the captcha authentication process for "Rest of the world". You can create the token with your login on their website and export / save it. 
https://bimmer-connected.readthedocs.io/en/stable/captcha/rest_of_world.html
As an interim solution, is there a way to "import" / swap that token with the current node red bmw function?

**Comment by jkellerer** [comment]
It anyone wants to give it a try, I have PR #43 running now and it started to work again. Had to wait 24 hours until login succeeded (without 429 error).

Will remove the draft flag from the PR when it runs stable for a couple of days.

**Comment by framps** [comment]
I grabbed your updated code. How do I generate a captcha token now?

**Comment by framps** [comment]
Just a comment: I get 429 now and my node-red doesn't start any more because of this. I suggest to catch the exception and create a message when a login error occurs. Otherwise NR terminates :wink: 

So I had to revert to the old code in order to get my NR up and running again. 

```
 Dec 17:56:23 - [red] Uncaught Exception:
8 Dec 17:56:23 - [error] Error: Server send http statusCode 429 on stage 1
    at Bmw._authenticate (/home/framp/.node-red/node_modules/node-red-contrib-car-bmw/lib/bmw.js:361:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bmw.requestNewToken (/home/peter/.node-red/node_modules/node-red-contrib-car-bmw/lib/bmw.js:772:20)
```

**Comment by jkellerer** [comment]
@framps , that is a weird result. 429 is expected after many failed login attempts. This should not stop NR though.

**Comment by framps** [comment]
Given I have no captcha defined because I don't know how to generate one it looks like your new code tried multiple times to connect and failed (See exception above). I noticed my NR then stops and restarts again. It took me a while to detect these NR restarts and to turn them off. Looks like there were too many attemps to connect without a captcha and now I'm also not able to test :cry:

**Comment by jkellerer** [comment]
@framps , think I found the problem. I added an eager login when a captcha is entered since it is valid only for a very short period of time. This caused the exception as it was unhandled. The PR (`bmw.js`) is updated now.

You can generate the captcha by clicking the one of the links (Rest of World or USA) in the yellow hint box (in the connected drive account settings). (Assuming you had updated the HTML file also)

**Comment by framps** [comment]
I now get
```
[node-red-contrib-car-bmw/Car-BMW] TypeError: Class constructor Bmw cannot be invoked without 'new'
```

**Comment by jkellerer** [comment]
Did you update all 3 files from the PR?
```
lib/bmw.js
car-bmw.js
car-bmw.html
```

**Comment by framps** [comment]
Yes. Initially I grabbed all of them and just now only bmw.js. That's the file you updated in your two last commits.

**Comment by jkellerer** [comment]
Did the log contain any additional details?

**Comment by framps** [comment]
```
8 Dec 18:51:00 - [info] Node-RED version: v3.1.7
8 Dec 18:51:00 - [info] Node.js  version: v18.20.5
8 Dec 18:51:00 - [info] Linux 6.6.31+rpt-rpi-v8 arm64 LE
8 Dec 18:51:01 - [info] Loading palette nodes
8 Dec 18:51:02 - [info] Dashboard version 3.6.5 started at /ui
8 Dec 18:51:03 - [warn] ------------------------------------------------------
8 Dec 18:51:03 - [warn] [node-red-contrib-car-bmw/Car-BMW] TypeError: Class constructor Bmw cannot be invoked without 'new'
8 Dec 18:51:03 - [warn] ------------------------------------------------------
8 Dec 18:51:03 - [info] Settings file  : /home/framp/.node-red/settings.js
8 Dec 18:51:03 - [info] Context store  : 'default' [module=memory]
8 Dec 18:51:03 - [info] User directory : /home/framp/.node-red
8 Dec 18:51:03 - [warn] Projects disabled : editorTheme.projects.enabled=false
8 Dec 18:51:03 - [info] Flows file     : /home/framp/.node-red/flows.json
8 Dec 18:51:03 - [info] Server now running at http://127.0.0.1:1880/
8 Dec 18:51:03 - [warn] Using unencrypted credentials
8 Dec 18:51:03 - [info] Waiting for missing types to be registered:
8 Dec 18:51:03 - [info]  - car-bmw
8 Dec 18:51:03 - [info]  - car-bmw-list
8 Dec 18:51:03 - [info]  - car-bmw-get
8 Dec 18:51:03 - [info]  - car-bmw-action
```
I will grab all 3 again. Just to make sure I copied all files in the correct directory.

**Comment by jkellerer** [comment]
should be:

```
node_modules/node-red-contrib-car-bmw/
  lib/
    bmw.js
  car-bmw.html
  car-bmw.js
```

**Comment by framps** [comment]
Now I get
```
8 Dec 19:06:21 - [red] Uncaught Exception:
8 Dec 19:06:21 - [error] Error: Server send http statusCode 401 on stage 1
    at Bmw._authenticate (/home/framp/.node-red/node_modules/node-red-contrib-car-bmw/lib/bmw.js:361:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bmw.requestNewToken (/home/framp/.node-red/node_modules/node-red-contrib-car-bmw/lib/bmw.js:776:20)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 8.908s CPU time.
```
and my NR doesn't start any more :-(

**Comment by framps** [comment]
Context store is now enabled:

```
8 Dec 19:15:11 - [info] Context store  : 'default' [module=localfilesystem]
```

**Comment by framps** [comment]
Now I was able to create a captcha but get
```
8 Dec 19:24:07 - [error] [car-bmw-list:BMW List] Error: No captcha token defined or already expired. Login not possible.
```
Maybe the message should should create dedicated message for missing and expired.

**Comment by framps** [comment]
Looks like you're offline now. NP. Just let me know when you have any update.

**Comment by framps** [comment]
I tried it again today with a valid captcha:

```
12/9/2024, 11:31:59 PM[node: BMW List](http://asterix:1880/#)
msg : error
"Error: No captcha token defined or already expired. Login not possible."
``

**Comment by jkellerer** [comment]
@framps, is the file `car-bmw.js` also updated in your env? It should pass the catcha token in the line `... = new Bmw(this.username, this.password, this.captcha, ...`.

**Comment by framps** [comment]
I'm neither a js nor node guy so I have no idea what's wrong because REGION_REST_OF_WORLD is defined as far as I can see.

```
framp@asterix:~/.node-red/node_modules/node-red-contrib-car-bmw $ grep -r REGION *
lib/bmw.js:  static REGION_REST_OF_WORLD = "0";
lib/bmw.js:  constructor(username, password, captchaToken = undefined, region = Bmw.REGION_REST_OF_WORLD, unit = Bmw.UNIT_METRIC) {
lib/bmw.js:      case Bmw.REGION_REST_OF_WORLD:  return 'b2vapi.bmwgroup.com';
lib/bmw.js:      case Bmw.REGION_REST_OF_WORLD:  return 'customer.bmwgroup.com';
lib/bmw.js:      case Bmw.REGION_REST_OF_WORLD:  return 'cocoapi.bmwgroup.com';
lib/bmw.js:          if (!this._captchaToken && (this._region == REGION_REST_OF_WORLD || this._region == REGION_USA)) {
```

**Comment by jkellerer** [comment]
> "Error: Server send http statusCode 401 on stage 1"

That means that either captcha or user & pw should be checked and inserted again.

**Comment by framps** [comment]
Well, I just updated the captcha because I thought the uid and pwd will be persistent in the config node.

Will now enter all 3 data and redeploy again.

**Comment by jkellerer** [comment]
These settings are persisted, that is correct. The only critical part is the captcha as it will be valid only for a short period of time.

**Comment by framps** [comment]
Success :smile: :+1: 

That's an important information you should document :wink: :
1) Enter pwd and captcha
2) redeploy flow

The userid is persisted in the config node.

**Comment by jkellerer** [comment]
Yes in fact I already documented it in the latest update to the HTML page as I thought that this might be the main reason why it didn't work :). Thanks a lot for testing it!

**Comment by framps** [comment]
> The only critical part is the captcha as it will be valid only for a short period of time.

Which means it's only required to enter the captcha an dredeploy? What's the validity of the captcha - I mean - how many time do I have between captcha generation and redeployment of the flow?

**Comment by jkellerer** [comment]
The code in `bmw.js` ignores the settings if it is older than 5 minutes. But I guess the CD servers will likely not accept it prior to this timeout.

**Comment by framps** [comment]
> Thanks a lot for testing it!

You're welcome :smiley: And thank you very much for your fix :+1:

**Comment by framps** [comment]
I just now created another captcha and didn't enter uid and pwd again. So it's sufficient to enter the captcha - **but** then redeploy the flow.

**Comment by jkellerer** [comment]
Exactly!

**Comment by framps** [comment]
Everything is persisted :clap: 
```
cat global.json 
{
    "bmw_oauth": {
        "277e0c1be839e9ee687798707856a4ce": {
            "captcha": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "state": 1,
            "updated": 1733855378004,
            "expires": 1733858962004,
            "type": "Bearer",
            "session": "e9757893-b869-4532-9610-ddddddddddddddd",
            "token": "xxxxxxxxxxxxxxxxxxxxxxxxx",
            "refresh": "yyyyyyyyyyyyyyyyyyyyyyyyy"
        }
    },
```

**Comment by framps** [comment]
Do you have any idea when your PR will be accepted?

**Comment by jkellerer** [comment]
No idea. It still is draft as I wanted to collect a bit more feedback and let it run a bit longer. It is a very heavy change after all as it requires a persistent state storage which was not required previously.

**Comment by framps** [comment]
> requires a persistent state storage

Yep. That's what I also missed to configure first. It's not difficult to configure but I suggest to document this also - if not documented already :smiley:

**Comment by framps** [comment]
> (The ref error I introduced due to code cleanup... should be fixed now. Had also added the info that the flow must be deployed in the form hint)

:+1:

**Comment by framps** [comment]
Just ping me if you want me to test and verify anything again.

**Comment by IfThenElseLoop** [comment]
Hi,
I also just tested with the updated files. It now works again. Great work and many thanks for the effort!
At the moment I tested only reading values (state), I will also try setting values as soon as possible.

**Comment by benninger1** [comment]
Tested also, sending commands will get this error: 
Error: Invalid data received: SyntaxError: Unexpected token 'o', "[object Promise]" is not valid JSON

**Comment by haegar33** [comment]
Looks like only one or two users have issues with this update. For my NodeRed Version 4.03 on a Raspberry Pi 3 everything works fine again. Unlike the original Bimmer code the captcha verification is retained even longer than 48hours (for now ;)
Thanks for the work!

**Comment by benninger1** [comment]
Now it's working like a charm! Thanks for your efforts! @jkellerer

**Comment by locke987** [comment]
I also tested successfully with the get state Node, thank you for fixing the issue!

**Comment by robee089** [comment]
@jkellerer: I found out that the configuration field "Storage" is not working. I have implemented two storage possibilities (memoryOnly and file) as in the tutorial context stores witch default "memoryOnly". As I understood I have to write than "file" in the field "Storage". But the value isn't saved and the data isn't stored on filesystem. After changing the default context store to "file" it works and it stores it on filesystem.

In other configuration-nodes (e.g. "node-red-persistent-values") the store is chosen with a drop down list with the user defined storage definitions. Perhaps you can change it like this.

**Comment by robee089** [comment]
the rest is working fine for me. Thank you for your great work

**Comment by jkellerer** [comment]
@robee089 , the `Storage` field should work now. A drop down to select could probably be done, however I'm not sure if it is worth the effort?

**Comment by krauskopf** [comment]
I just published the nodes to the Node-RED registry. Thanks to @jkellerer for this fix. All credits to him.

**Comment by ChrisIDS6** [comment]
Many Thanks to all to you...
It seems to work - nodered get all the needed data....
hopefully it works for a long time ;)

**Comment by rsteininger** [comment]
hi there. works great with the implementation of the captcha. I am operating node-red in a docker environment, and node red and docker container restarts are no problem! However, when I remove and update the node-red image, the bmw node "loses" it's captcha information. My other persistent node data is not impacted by the docker image removal / reinstallation as it is stored in \data in a persistent docker volume. Is there anything I can do to make the captcha "survive" the image update / container removal, e.g. have the captcha stored in the persistent \data folder? My default setting in node red is already persistent storage.
Any advice / guidance would be greatly appreciated.

**Comment by jkellerer** [comment]
> hi there. works great with the implementation of the captcha. I am operating node-red in a docker environment, and node red and docker container restarts are no problem! However, when I remove and update the node-red image, the bmw node "loses" it's captcha information. ...

Hi @rsteininger, if no explicit storage is selected, the captcha and session information is stored in the global context of the default storage. You can search for the keyword `"bmw_oauth": {` e.g.:

```shell
docker compose exec nodered-car-app bash
2d9460cc92ea:~$ grep '"bmw_oauth": {' -r /data/
/data/context/global/global.json:    "bmw_oauth": {
```

.. and finally check if this file is in a volume that is retained (assuming a [context store](https://nodered.org/docs/user-guide/context#context-stores) was setup).

**Comment by rsteininger** [comment]
Many thanks @jkellerer!
It seems all is there and I am guessing I know what happened. 
When I manually reboot the system, it is only "down" for about 3 minutes. 

However, I was traveling and my wife notified me that the home automation system was down. By the time I was able to log in, remove the container and restart node-red, I'd say at least 2 hours or so had passed. Would I be right in assuming, that without "regular" use of the bmw node (node red was down), the captcha might have expired by the time the container was back up and running? 

THANKS!

**Comment by jkellerer** [comment]
Yes a regular refresh of the tokens is required. If nodered is off for too long the captcha has to be renewed.
