### ISSUE TITLE
statusCode 410 Error

### ISSUE THREAD

**Issue by Donni1966** [krauskopf/node-red-contrib-car-bmw#9]
Hi 
i get may be last two days this error

`Error: Server http statusCode 410`

when i trigger "last trip" o "all trips"

any idea ?

if needful i can try to provide with al log file ... 

byby, Michael

**Comment by Toxo666** [comment]
the same goes for me.

all urls show 404/410

https://vector.hereapi.com/
https://api.countly.bmwgroup.com/
http://cocoapi.bmwgroup.com/

**Comment by CONSULitAS** [comment]
There seem to be major changes needed to connect to a new API.

Just found this library which seems to work still:
https://github.com/bimmerconnected/bimmer_connected

This commit 
https://github.com/bimmerconnected/bimmer_connected/commit/5652c8a50d654d9a3557e8e77aea354aab98c835

shows completely new URLs here:
https://github.com/bimmerconnected/bimmer_connected/commit/5652c8a50d654d9a3557e8e77aea354aab98c835#diff-126093b6a282d2f3ad167e598e134c689df8e188630540cf5efb6107b409acce

The library has a CLI (https://bimmer-connected.readthedocs.io/en/latest/cli.html) which could be called via the excec node...

**Comment by CONSULitAS** [comment]
So lets see what happens:

`>bimmerconnected status my@email.com  mypassword rest_of_world`

shows a lot of debug information (some debug information removed for ):

```
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cocoapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-ucs/v1/presentation/oauth/config HTTP/1.1" 200 580
DEBUG:bimmer_connected.account:Authenticating against GCDM with MyBMW flow.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): customer.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://customer.bmwgroup.com:443 "POST /gcdm/oauth/authenticate HTTP/1.1" 200 411
DEBUG:urllib3.connectionpool:https://customer.bmwgroup.com:443 "POST /gcdm/oauth/authenticate HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://customer.bmwgroup.com:443 "POST /gcdm/oauth/token HTTP/1.1" 200 1949
DEBUG:bimmer_connected.account:got new token 75AxlDCpOyya7qT-mcS12pWZoCE with expiration date 2021-12-01 18:08:27.269480
DEBUG:bimmer_connected.account:Request to: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cocoapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638374908.350597&tireGuardMode=ENABLED HTTP/1.1" 200 7854
DEBUG:bimmer_connected.account:Request to: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cocoapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638374909.869302&tireGuardMode=ENABLED HTTP/1.1" 200 2
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:Request to: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cocoapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638374911.215579&tireGuardMode=ENABLED HTTP/1.1" 200 7854
DEBUG:bimmer_connected.account:Request to: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cocoapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638374912.571924&tireGuardMode=ENABLED HTTP/1.1" 200 2
Found 1 vehicles: i3 (+ REX)
VIN: WBY1Z41080VZ12345
Mileage: (12345, 'km')
Vehicle data:
DEBUG:bimmer_connected.vehicle_status:No data available for attribute <function VehicleStatus.fuel_percent at 0x10f99f280>!
```

This is followed by a huge JSON string with all the interesting things. 😁 But the structure is not the same. Looks like a lot of work to be done!

**Comment by krauskopf** [comment]
I will have a look at it at the comming weekend ;-)

**Comment by bbwouters** [comment]
Same here, looks like some changes still need to be implemeted

**Comment by krauskopf** [comment]
Sorry, took some more weekends than expected until I had a chance to look into it. 
Thanks to @CONSULitAS for the links. That was helpful. I have adjusted the code and replaced it with the new API endpoints.
You want to give it a try by upgrading to v0.3.2.

**Comment by Donni1966** [comment]
Hi, 

i test it. but where ist lasttrip and alltrips?  

i found the may be news charting statistics - nice.
